### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wealeson1** [theblackturtle/fprobe#1]
root@iZ2zef4xnm6qgkyshlh1bkZ:~# GO111MODULE=on go get -u github.com/theblackturtle/fprobe
go: github.com/theblackturtle/fprobe upgrade => v0.0.0-20200410160818-9e3a3c448d36
go: github.com/klauspost/cpuid upgrade => v1.2.3
go: github.com/klauspost/compress upgrade => v1.10.4
go: github.com/modern-go/reflect2 upgrade => v1.0.1
go: github.com/panjf2000/ants upgrade => v1.3.0
go: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
**# github.com/theblackturtle/fprobe
go/pkg/mod/github.com/theblackturtle/fprobe@v0.0.0-20200410160818-9e3a3c448d36/main.go:87:13: undefined: ants.NewPoolWithFuncPreMalloc**

**Comment by theblackturtle** [comment]
Hi, Can you reinstall again. I fixed go.mod file
